CREATE TABLE sales_uploads (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  store_id BIGINT UNSIGNED NOT NULL,
  requested_by_user_id BIGINT UNSIGNED NOT NULL,
  original_file_name VARCHAR(255) NOT NULL,
  storage_key VARCHAR(512) NOT NULL,
  file_checksum VARCHAR(64) NOT NULL,
  status VARCHAR(20) NOT NULL,
  processing_phase VARCHAR(20) NULL,
  period_start DATE NULL,
  period_end DATE NULL,
  total_row_count BIGINT NOT NULL DEFAULT 0,
  valid_row_count BIGINT NOT NULL DEFAULT 0,
  invalid_row_count BIGINT NOT NULL DEFAULT 0,
  error_code VARCHAR(50) NULL,
  error_message TEXT NULL,
  uploaded_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  processed_at DATETIME NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_sales_uploads_storage_key (storage_key),
  KEY idx_sales_uploads_store_uploaded_at (store_id, uploaded_at),
  KEY idx_sales_uploads_store_period (store_id, period_start, period_end),
  KEY idx_sales_uploads_store_checksum (store_id, file_checksum),
  CONSTRAINT fk_sales_uploads_store FOREIGN KEY (store_id) REFERENCES stores(id),
  CONSTRAINT fk_sales_uploads_user FOREIGN KEY (requested_by_user_id) REFERENCES users(id)
) ENGINE=InnoDB;

CREATE TABLE sales_orders (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  sales_upload_id BIGINT UNSIGNED NOT NULL,
  store_id BIGINT UNSIGNED NOT NULL,
  channel VARCHAR(20) NOT NULL,
  pos_order_no VARCHAR(100) NOT NULL,
  ordered_at DATETIME NOT NULL,
  is_valid BOOLEAN NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_sales_orders_natural_key (store_id, channel, pos_order_no, ordered_at),
  CONSTRAINT fk_sales_orders_upload FOREIGN KEY (sales_upload_id) REFERENCES sales_uploads(id),
  CONSTRAINT fk_sales_orders_store FOREIGN KEY (store_id) REFERENCES stores(id)
) ENGINE=InnoDB;

CREATE TABLE sales_order_items (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  sales_order_id BIGINT UNSIGNED NOT NULL,
  menu_id BIGINT UNSIGNED NULL,
  order_status VARCHAR(20) NOT NULL,
  menu_name_raw VARCHAR(255) NOT NULL,
  menu_name VARCHAR(100) NOT NULL,
  menu_key VARCHAR(191) NOT NULL,
  category_raw VARCHAR(100) NULL,
  standard_category VARCHAR(30) NOT NULL,
  option_raw VARCHAR(500) NULL,
  quantity INT NOT NULL,
  line_price BIGINT NOT NULL,
  unit_price BIGINT NOT NULL,
  option_price BIGINT NOT NULL,
  item_discount_name VARCHAR(100) NULL,
  item_discount_amount BIGINT NOT NULL,
  order_discount_name VARCHAR(100) NULL,
  order_discount_amount BIGINT NOT NULL,
  net_amount BIGINT NOT NULL,
  taxable BOOLEAN NOT NULL,
  vat_amount BIGINT NOT NULL,
  item_type VARCHAR(30) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_sales_order_items_order (sales_order_id),
  CONSTRAINT fk_sales_order_items_order FOREIGN KEY (sales_order_id) REFERENCES sales_orders(id)
) ENGINE=InnoDB;

CREATE TABLE sales_daily_summaries (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  store_id BIGINT UNSIGNED NOT NULL,
  sales_date DATE NOT NULL,
  total_net_amount BIGINT NOT NULL,
  menu_net_amount BIGINT NOT NULL,
  order_count INT NOT NULL,
  menu_quantity INT NOT NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_sales_daily_summaries_store_date (store_id, sales_date),
  CONSTRAINT fk_sales_daily_summaries_store FOREIGN KEY (store_id) REFERENCES stores(id)
) ENGINE=InnoDB;

CREATE TABLE analysis_runs (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  store_id BIGINT UNSIGNED NOT NULL,
  requested_by_user_id BIGINT UNSIGNED NOT NULL,
  based_on_upload_id BIGINT UNSIGNED NOT NULL,
  analysis_type VARCHAR(20) NOT NULL,
  status VARCHAR(20) NOT NULL,
  period_start DATE NULL,
  period_end DATE NULL,
  engine_version VARCHAR(50) NOT NULL,
  idempotency_key VARCHAR(100) NOT NULL,
  error_message VARCHAR(500) NULL,
  started_at DATETIME NULL,
  completed_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_analysis_runs_idempotency_key (idempotency_key),
  KEY idx_analysis_runs_store_completed (store_id, completed_at),
  CONSTRAINT fk_analysis_runs_store FOREIGN KEY (store_id) REFERENCES stores(id),
  CONSTRAINT fk_analysis_runs_user FOREIGN KEY (requested_by_user_id) REFERENCES users(id),
  CONSTRAINT fk_analysis_runs_upload FOREIGN KEY (based_on_upload_id) REFERENCES sales_uploads(id)
) ENGINE=InnoDB;
